Workspaces pinned tabs
Glue42/core pull request #159
Opened 2020-11-19 13:19 UTC by SvetozarMateev

## New template - workspaces-react-pinned-tabs
Added a template that uses the new noTabHeader property and custom react buttons to showcase how can pinned tabs be implemented.

## New extension point in workspaces-react-ui
The components object now has a WorkspaceContents property which in combination with the `<WorkspaceContents/>` component provided by the library enables composition and conditional rendering of the workspace contents.

## Workspaces selected event
Added the `frame.onWorkspaceSelected()` event which is triggered when a workspace has been selected.

2020-11-19 15:32 UTC, ggeorgievx approved these changes

2020-11-20 09:12 UTC, flashd2n requested changes

2020-11-20 09:12 UTC, flashd2n commented on packages/workspaces-api/workspaces.d.ts
> +        /** Provides the opportunity to open a workspace with a workspace tab header */
with **no** tab header

2020-11-20 09:12 UTC, flashd2n commented on packages/workspaces-api/workspaces.d.ts
> +         * @param callback Callback function to handle the event. Receives the added workspace as a parameter.
received the **selected** workspace

2020-11-20 09:12 UTC, flashd2n commented on e2e/tests/Workspaces/Frame/onWorkspaceSelected.spec.js
> +    it.only('not be invoked when a workspace with noTabHeader:true is restored', (done) => {
why .only

2020-11-20 09:12 UTC, flashd2n commented on e2e/tests/Workspaces/Frame/onWorkspaceSelected.spec.js
> +            if (newWorkspace && w.id === newWorkspace.id) {
you don't need the if check here -> we should fail if the event is fired, no matter the args.

2020-11-20 09:12 UTC, flashd2n commented on e2e/tests/Workspaces/Frame/onWorkspaceSelected.spec.js
> +                if (newWorkspace && w.id === newWorkspace.id) {
same as above -  no need for if statement

2020-11-20 09:12 UTC, flashd2n commented on e2e/tests/Workspaces/Frame/onWorkspaceSelected.spec.js
> +describe('frame.onWorkspaceSelected() Should ', () => {
every test needs to have the ready resolve condition (multiple ready invocations before marking the test as done)

2020-11-20 09:12 UTC, flashd2n commented on e2e/tests/Workspaces/Frame/onWorkspaceSelected.spec.js
> +            defaultFrame.createWorkspace(basicConfig).then(() => {
unnecessary nesting. return the createWorkspace invocations and chain the then.

2020-11-20 09:12 UTC, flashd2n commented on e2e/tests/Workspaces/Frame/onWorkspaceSelected.spec.js
> +                    if (w.id === firstWorkspace.id) {
unnecessary if

2020-11-20 10:20 UTC, flashd2n requested changes

2020-11-20 10:20 UTC, flashd2n commented on e2e/tests/Workspaces/Frame/onWorkspaceSelected.spec.js
> +            defaultFrame.createWorkspace(basicConfig);
missing return

2020-11-20 10:46 UTC, flashd2n approved these changes

2020-11-20 13:18 UTC, merged