Fix AppManager tests
Glue42/core pull request #442
Opened 2022-07-19 07:28 UTC by ksgeorgieva

Update of the **AppManager API** tests

2022-07-22 07:30 UTC, flashd2n requested changes

2022-07-22 07:30 UTC, flashd2n commented on e2e/tests/appManager/API/onInstanceStarted.spec.js
> +                const un = glue.appManager.onInstanceStarted(invalidArg);
false positive

2022-07-22 07:30 UTC, flashd2n commented on e2e/tests/appManager/API/onInstanceStarted.spec.js
> +        const ready = gtf.waitFor(3, done);
false positive

2022-07-22 07:30 UTC, flashd2n commented on e2e/tests/appManager/API/onInstanceStopped.spec.js
> +        const ready = gtf.waitFor(3, done);
false positive

2022-07-22 07:30 UTC, flashd2n commented on e2e/tests/appManager/API/onInstanceStopped.spec.js
> +        const ready = gtf.waitFor(2, done);
Test in wrong spec

2022-07-24 13:04 UTC, ksgeorgieva commented on e2e/tests/appManager/API/onAppChanged.spec.js
> +        const ready = gtf.waitFor(2, done);
There's an application definition with such name passed to the config object at the initialization of the Web Platform when starting GTF. See https://github.com/Glue42/core/blob/master/e2e/config/gtf/config.ts#L73  and https://github.com/Glue42/core/blob/master/e2e/config/gtf/index.ts#L95

The merged **extraDefOne** app definition changes the **url** property of the "Test" app and triggers **onAppChanged()**

2022-07-25 19:01 UTC, flashd2n requested changes

2022-07-27 07:56 UTC, flashd2n approved these changes

2022-07-27 07:56 UTC, merged