Extending js tutorial
Glue42/core pull request #484
Opened 2022-09-08 12:38 UTC by AleksTanev

2022-09-13 11:03 UTC, flashd2n requested changes
1. Extract the plugin into a separate file
2. Keep the `includeInWorkspaces` explanation
3. Rework the intents so that the intent is registered by a dedicated app - also make it export, instead of download

2022-09-13 11:55 UTC, AleksTanev commented
I'm on it

2022-09-29 09:00 UTC, flashd2n requested changes

2022-09-29 09:00 UTC, flashd2n commented on tutorials/javascript/start/Clients/plugins/applicationsPlugin.js
> +const fetchAppDefinitions = async (url) => {
should be created by the user

2022-09-29 09:00 UTC, flashd2n commented on tutorials/javascript/start/Clients/plugins/layoutsPlugin.js
> +const setupLayouts = async (glue, { url }) => {
should be created by the user

2022-09-29 09:00 UTC, flashd2n commented on tutorials/javascript/start/client-details/index.html
> +        <a id="download" download="clientPortfolio.json" style="display:none"></a>
to remove

2022-09-29 13:49 UTC, AleksTanev commented on tutorials/javascript/start/client-details/index.html
> +        <a id="download" download="clientPortfolio.json" style="display:none"></a>
done!

2022-10-18 08:23 UTC, flashd2n approved these changes

2022-10-18 09:16 UTC, merged