Add lock events
Glue42/core pull request #502
Opened 2022-10-05 11:07 UTC by SvetozarMateev

## WorkspaceTabV2
Changed the default workspace tab with a new and improved version, which in addition to the save popup has a locking settings popup
![image](https://user-images.githubusercontent.com/25162335/194045604-e80962ff-2cad-49ca-a819-6b325194dee3.png)

## Locking events
Added locking events for any changes in the configuration on window, box and workspace level

2022-10-05 11:57 UTC, arjunah requested changes
The following needs consideration:
- on/off UI logic of lock buttons - maybe change with "lock/unlock" icons instead of slide buttons;
- capitalize first letter of all names in the UI;
- Disable all -> Lock All;
- decide on using either "lock" or "lockdown" instead of "locking" in the UI and the code;

2022-10-06 16:02 UTC, flashd2n requested changes
Also squash all commit when ready pls

2022-10-06 16:02 UTC, flashd2n commented on e2e/tests/workspaces/API/createWorkspace.spec.js
> +                            appName: "noGlueApp"
Why are we switching from a dummy glue client to a non-glue dummy client

2022-10-06 19:06 UTC, flashd2n approved these changes

2022-10-06 19:06 UTC, merged